<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="23590" started-at="2022-01-06T19:23:11 IST" finished-at="2022-01-06T19:23:34 IST">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.runner.TestRunner@77f99a05]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Test" duration-ms="23590" started-at="2022-01-06T19:23:11 IST" finished-at="2022-01-06T19:23:34 IST">
      <class name="com.runner.TestRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:com.runner.TestRunner@77f99a05]" name="setUpClass" is-config="true" duration-ms="558" started-at="2022-01-06T19:23:11 IST" finished-at="2022-01-06T19:23:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.runner.TestRunner@77f99a05]" name="runScenario" duration-ms="20765" started-at="2022-01-06T19:23:11 IST" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2022-01-06T19:23:32 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify Count Down Timer is running for given seconds"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[Verify count Down timer is running for given time]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [11] but found [9]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [11] but found [9]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.countdown.pages.CountDownTimerPage.verifyCountDownTime(CountDownTimerPage.java:82)
at com.countdown.pages.CountDownTimerPage.VerifyCountDownTimer(CountDownTimerPage.java:44)
at com.countdown.stepdef.CountDownTimeSteps.count_timer_should_gets_starts_and_it_should_decrement_by_sec(CountDownTimeSteps.java:66)
at âœ½.Count Timer should gets starts and it should decrement by 1-sec(file:///D:/EclipseLatest/CountDownTimer/src/test/resources/features/CountDownTimer.feature:10)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:com.runner.TestRunner@77f99a05]" name="tearDownClass" is-config="true" duration-ms="2213" started-at="2022-01-06T19:23:32 IST" finished-at="2022-01-06T19:23:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.runner.TestRunner -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
